# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8677c93194971397ccf425de57566bcdc8201ccbda5bfa89cb0054a560829be167fadd8fd872b9dca182c16471a9318f6df42391f804c53f7de40f23161902a

test:
  secret_key_base: 2397d160324d6a169bd0fcfa0a1a51a3f37a4f7821b023ef6edef38ae522ad599535fa80c6b7b2e185d9abf5fb656585b2d0da7037651891c800566da2119aa2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
